server:
  port: 8081
spring:
  application:
    name: ai-avatar-core
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_avatar?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: hcxh8888@@
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /