server:
  port: 8081
spring:
  application:
    name: ai-avatar-core
  mvc:
    servlet:
      path: /api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_avatar?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: hcxh8888@@
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: auto

tx:
  cos:
    secret-id: AKIDSn1FORM4bu0wfBUd4KOFsIUTF0Yw62lJ
    secret-key: PfiYAbqrfFC9tPkslRuAC1c0c1IMEvTo
    region: ap-shanghai


