server:
  port: 8080

spring:
  application:
    name: ai-avatar-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/**
        - id: core-service
          uri: http://localhost:8081
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_avatar?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: hcxh8888@@
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.aiavatar.**.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

tencent:
  cos:
    secret-id: ${COS_SECRET_ID:your-secret-id}
    secret-key: ${COS_SECRET_KEY:your-secret-key}
    region: ap-guangzhou
    bucket-name: your-bucket-name 

wx:
  pay:
    appId: your-app-id
    mchId: your-mch-id
    mchKey: your-mch-key
    keyPath: classpath:cert/apiclient_cert.p12
    notifyUrl: https://your-domain.com/api/v1/payment/notify 