server:
  port: 8082
spring:
  application:
    name: ai-avatar-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_avatar?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: hcxh8888@@
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

wx:
  miniapp:
    appid: wxa738fb7ee7af0358
    secret: e79d94dcf814fb8eee466511f4a68aa8
    token: ${WX_MINIAPP_TOKEN}
    aesKey: ${WX_MINIAPP_AES_KEY}
    msgDataFormat: JSON